version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smallstore-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: smallstore_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: smallstore-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smallstore.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  pgdata:
